spring:
  application:
    name: user-service

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
